### PR TITLE
fix: missing comma

### PR DESCRIPTION
**Pull request by kamilkisiela**
It's causing error in npm angular2-now@0.3.17

@pbastowski Do you need any unit tests? I could do some work if you want.

### CODE REVIEW

**Comment by kamilkisiela** [comment]
I checked cache of angular2-now@0.3.17 meteor package and there is the same error.

So I think it's related to #31 issue

**Comment by pbastowski** [comment]
:+1: the code could definitely use some unit tests.

**Comment by kamilkisiela** [comment]
@pbastowski Do you have any requirements about testing cases? Karma, velocity (but deprecated) or tinytest?

**Comment by pbastowski** [comment]
I haven't been writing any tests for the past several months, so, I'm out of date on what's the best setup to use. What is the industry best practice currently?

**Comment by kamilkisiela** [comment]
I think unit testing using node and karma (with jasmine or mocha) instead of meteor would be the best option. At the moment there is no official testing framework in meteor. 

I will give you access to my repo so you can check progress.
https://github.com/kamilkisiela/angular2-now/tree/feature/unit-tests

**Comment by pbastowski** [comment]
We use npm and karma with jasmine at work also. Some use mocha, but mainly jasmine. Sounds like a plan!

If you're going to make test and possible changes then you please have a look at the meteor1.2 branch, because that's the one that I want to take to npm next. Its mostly the same, but it also knows how to register itself with SystemJS, if it's loaded already.

Thanks.

**Comment by kamilkisiela** [comment]
@pbastowski So basically, I should create new branch from meteor1.2 branch?

**Comment by pbastowski** [comment]
Actually, having just thought about it, I'm not sure the `meteor1.2` branch will work in its current form with SystemJS. The `meteor1.2` branch self registers itself with SystemJS when it detects `System`, so, not sure if this will break things.

... and I have to go shopping right now, so, can't look into this either.

Perhaps you'd like to try?

You'd need to:
- create a new test project
- clone angular2-now into a local folder
- checkout branch `meteor1.2`
- then try to load angular2-now with SystemJS into your test app
- and use it to prove that it actually works.

**Comment by kamilkisiela** [comment]
@pbastowski I'm going to look it up.

I'm currently setting up karma. Beside tests, you'll have code covarage also :)

I've used webpack to simplify babel compiling process. 

I also left space for other configurations so if in the near future you would want to add some build process (minification etc) it will be a lot easier :)

You can find me on gitter ([@kamilkisiela](http://gitter.im/kamilkisiela)) if you don't want to keep posting new messages in this pull request.

**Pull request merged**
