### PR TITLE
Unit testing

### PR DESCRIPTION
**Pull request by kamilkisiela**
Hi, @pbastowski !

As i promised, here are tests with 75% code coverage.

You should be aware that I set npm package as private to prevent publishing.

---

I used:
- karma and jasmine for testing
- webpack with:
  - babel loader to compile code before testing
  - istanbul loader for code coverage support
## npm scripts:

**Run tests on CI** (you can also use it locally)

singleRun: true
autowatch: false
launcher: firefox

> $ npm **test**

**Run tests locally** 

singleRun: false
autowatch: true
launcher: chrome

> $ npm run **test:local**

**Update code coverage**

I used coveralls.io just to have the view on code.

> $ npm run **coverage:coveralls**

---
## Travis:

I added example travis configuration

https://travis-ci.org/kamilkisiela/angular2-now
## Code coverage:

https://coveralls.io/github/kamilkisiela/angular2-now

### CODE REVIEW

**Comment by pbastowski** [comment]
Hi Kamil. Anything wrong with the PR? I was going to merge it later today.

**Comment by kamilkisiela** [comment]
@pbastowski Oh, my mistake :)

**Comment by pbastowski** [comment]
Really nice work, Kamil. Thank you very much for doing this.

**Comment by jacobdr** [comment]
image

**Comment by kamilkisiela** [comment]
It's 85% code coverage now. It's mostly for basic functionality. The special cases need to be done.

**Pull request merged**
