### PR TITLE
Ported to TypeScript

### PR DESCRIPTION
**Pull request by nalbion**
As I understand it, the Angular2 team have adopted TypeScript.  I've been looking into TypeScript and I think that the type annotations make it easier for other developers to use libraries and refactor large code bases.

I've added a `gulpfile.js` which will convert `angular2-now.ts` into a RequireJS-friendly `angular2-now.js`

### CODE REVIEW

**Comment by pbastowski** [comment]
Hi Nicholas(@nalbion). Sydney is one of my favourite cities that I ever lived and worked in. Do you still live/work there ? 

And now, back to the topic. I have read your message and I would like to understand what you actually propose.
1) Do you wish provide a TypeScript version of the library along side of my existing ES6/Babel version?
2) Do you wish to replace my existing ES6 version with the TypeScript version and provide a RequireJS-friendly angular2-now.js?
3) Are you suggesting to replace the current `window.angular2now` global export with a `RequireJS` setup?

I would welcome a separate TypeScript version of the library to the project. However, I will continue developing the ES6/Babel version for the moment. So, I envisage further conversions of angular2-now from ES6 to TypeScript in the future.

Also, how would making the library RequireJS friendly make it also compatible with non-RequireJS setups, such as Meteor packages, SystemJS/ES6 module loader and plain vanilla JavaScript?

Paul

**Comment by nalbion** [comment]
Hi Paul, yes I do live in Sydney, I'm glad you enjoyed your time here.

Perhaps the ideal scenario would be that you maintain the TypeScript code and have a gulp task which transpiles it to JavaScript that can be handled by Meteor.

**Comment by pbastowski** [comment]
Yeah, I thought you might say that. For now I will stick with ES6/Babel. 

I get that the the Angular2 team have adopted TypeScript, but I am not ready to do so just yet :)

However, we could add an ES6 to TS conversion task in the gulp file, to create a TS version. And another set of tasks that removes my wrapper and adds a RequireJS, SystemJS or other module loader support

People could create pull requests to add further tasks that support other module loader formats.

Is this something that you could live with?

**Comment by nalbion** [comment]
surely it would be easier to transpile down from TypeScript to ES6 and ES5.  That way you'd lose the type annotations and select a different module system and then swap your wrapper for Meteor.

Going the other way would be a lot more work and you'd have to mark all types as optional `any`

**Comment by pbastowski** [comment]
I'm closing this PR, because currently I have no plans to adopt TypeScript as the main source, with transpiling to ES6/ES5 as the result.

**Pull request closed without merging**
