### PR TITLE
feat(states): add support for custom data

### PR DESCRIPTION
**Pull request by aaronroberson**
UI-router custom data support https://github.com/angular-ui/ui-router/wiki#attach-custom-data-to-state-objects

### CODE REVIEW

**Comment by aaronroberson** [comment]
Does the version need to be bumped in order to pull down the latest with Meteor?

**Comment by pbastowski** [comment]
Yeah. I need to bump it and then publish it to Meteor. Give me 5.

**Comment by aaronroberson** [comment]
Thanks!

**Comment by pbastowski** [comment]
Done

**Pull request merged**
